---
title: "case1"
output: html_document
date: "2026-04-17"
---
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(tibble)
```
 
```{r}
#IMPORT DATA AND CREATE RAW TABLE
lines <- readLines("C:/Users/nicol/Downloads/supermarket/supermarket.csv")

supermarket_raw <- tibble(
  transaction_id = 1:length(lines),
  basket = lines
)

head(supermarket_raw)

#TRANSFORM EACH TRANSACTION INTO SINGLE SCANS
long_data <- supermarket_raw %>%
  separate_rows(basket, sep = ",") %>%
  mutate(basket = str_trim(basket)) %>%
  filter(basket != "")

#SEPARATE (D, T, P)
long_data <- long_data %>%
  separate(
    basket,
    into = c("department", "time", "price"),
    sep = "\\s+"
  )

#CONVERT NUMERIC
long_data <- long_data %>%
  mutate(
    department = as.numeric(department),
    time = as.numeric(time),
    price = as.numeric(price)
  )

#CREATE STEP VARIABLE
long_data <- long_data %>%
  group_by(transaction_id) %>%
  mutate(step = row_number()) %>%
  ungroup()

#SELECT FINAL COLUMNS
long_data <- long_data %>%
  select(transaction_id, step, department, time, price)

head(long_data)
str(long_data)
summary(long_data)
length(unique(long_data$transaction_id))
```

```{r}
#MAP DEPARTMENT CODES TO NAMES
dept_map <- c(
  "1" = "Bakery & Pastry",
  "2" = "Beer & Wine",
  "3" = "Books & Magazines",
  "4" = "Candy & Chips",
  "5" = "Care & Hygiene",
  "6" = "Cereals & Spreads",
  "7" = "Cheese & Tapas",
  "8" = "Dairy & Eggs",
  "9" = "Freezer",
  "10" = "Fruit & Vegetables",
  "11" = "Household & Pet",
  "12" = "Meat & Fish",
  "13" = "Pasta & Rice",
  "14" = "Salads & Meals",
  "15" = "Sauces & Spices",
  "16" = "Soda & Juices",
  "17" = "Special Diet",
  "18" = "Vegetarian & Vegan"
)

long_data <- long_data %>%
  mutate(department_name = dept_map[as.character(department)])
head(long_data)
```
```{r}
#CREATE BASKET-LEVEL FEATURES
basket_data <- long_data %>%
  group_by(transaction_id) %>%
  summarise(
    total_items = n(),
    total_price = sum(price, na.rm = TRUE),
    avg_price = mean(price, na.rm = TRUE),
    total_time = sum(time, na.rm = TRUE)
  ) %>%
  mutate(
    price_per_second = total_price / total_time
  )

head(basket_data)
str(basket_data)
summary(basket_data)
```





